version: '2'
services:
  s3sync:
    image: vladgh/s3sync:0.4
    env_file: bootstrap/s3sync.env
    command: sync
    environment:
      - SYNCDIR=/data/ARK-Backups
    volumes:
      - ./data:/data
  ark:
    build: 
      context: .
    tty: true
    restart: on-failure
    network_mode: host
    #cpuset: '0-7'
    stop_grace_period: 10m
    stop_signal: SIGTERM
    volumes:
      - ./data:/home/steam
      - ./bootstrap:/bootstrap:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    ulimits:
      nproc: 100000
      nofile:
        soft: 100000
        hard: 100000
